name: base
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py38h27cfd23_1003
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda=4.10.3=py38h06a4308_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - idna=2.10=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py38h06a4308_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==1.0.0
    - anyio==3.4.0
    - argon2-cffi==21.1.0
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - bypy==1.7.12
    - cachetools==4.2.4
    - cycler==0.11.0
    - cython==0.29.28
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - dill==0.3.4
    - entrypoints==0.3
    - fonttools==4.28.2
    - ftfy==6.1.1
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - importlib-metadata==4.8.2
    - importlib-resources==5.4.0
    - ipykernel==6.5.1
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.1
    - jinja2==3.0.3
    - json5==0.9.6
    - jsonschema==4.2.1
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - jupyter-server==1.12.0
    - jupyterlab==3.2.4
    - jupyterlab-language-pack-zh-cn==3.2.post2
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.5.0
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multiprocess==0.70.12.2
    - nbclassic==0.3.4
    - nbclient==0.5.9
    - nbconvert==6.3.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - ninja==1.10.2.3
    - notebook==6.4.6
    - numpy==1.21.4
    - oauthlib==3.1.1
    - opencv-python==4.5.5.62
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.4.0
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.22
    - protobuf==3.19.1
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.10.0
    - pyparsing==3.0.6
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyzmq==22.3.0
    - regex==2022.1.18
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rsa==4.8
    - scipy==1.8.0
    - send2trash==1.8.0
    - setuptools-scm==6.3.2
    - sniffio==1.2.0
    - supervisor==4.2.2
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.12.1
    - testpath==0.5.0
    - tomli==1.2.2
    - torch==1.10.0+cu113
    - torchvision==0.11.1+cu113
    - tornado==6.1
    - traitlets==5.1.1
    - typing-extensions==4.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - zipp==3.6.0
prefix: /root/miniconda3